package com.github.saleco.oop.organazedpackages.beans

@groovy.transform.ToString
class Employee implements Serializable {

    String first, last, email
    String fullName

    //you can override getter and setters auto generated by groovy
    void setFullName(String name) {
        fullName = name
    }

    String getFullName() {
        "Full Name: $fullName"
    }
}
